spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kea_clubs_dev
    username: root
    password: toor
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true